laszlo_demo:
  outputs:
    dev:
      type: postgres
      threads: 4
      host: company_dw
      port: 5432
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: company_dw
      schema: "{{ env_var('DBT_SCHEMA', 'dev') }}"  # Default to 'dev' if DBT_SCHEMA is not set
  target: dev