import os

SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')

# Postgres DWH connection URI
COMPANY_DW_SQLALCHEMY_URI = os.getenv('POSTGRES_DATABASE_URI')


SECRET_KEY = os.getenv('SUPERSET_SECRET_KEY')

ALERT_REPORTS = True